/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class pairing_crypto_Stub */

#ifndef _Included_pairing_crypto_Stub
#define _Included_pairing_crypto_Stub
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     pairing_crypto_Stub
 * Method:    add
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_pairing_1crypto_Stub_add
  (JNIEnv *, jclass, jlong, jlong);

#ifdef __cplusplus
}
#endif
#endif
