[package]
name = "paring_crypto_cpp"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cxx = "1.0.110"
pairing_crypto = { path = "../../", version = "0.4.2" }

[build-dependencies]
cxx-build = "1.0"
